name: airports
replicaCount: 1
image:
  repository: 851725191021.dkr.ecr.us-east-2.amazonaws.com/airports
  pullPolicy: Always
  tag: "latest"
podAnnotations:
  linkerd.io/inject: disabled
podSecurityContext: {}
service:
 type: NodePort
 port: 8000
 targetport: 8080
resources: 
  requests:
    cpu: 100m
    memory: 200m
container:
        port: 8080
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
namespace: "airports"
##for liveness and readiness  
path: "/health/live"
port: 8080
