name: airports
replicaCount: 1
image:
  repository: 727245885999.dkr.ecr.us-east-2.amazonaws.com/drone
  pullPolicy: Always
  tag: "1.0.3_drone"
podAnnotations:
  linkerd.io/inject: disabled
podSecurityContext: {}
service:
 type: NodePort
 port: 8000
 targetport: 8080
resources: 
  requests:
    cpu: 100m
    memory: 200m
container:
        port: 8080
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
namespace: "drone"
##for liveness and readiness  
path: "/health/live"
port: 8080
